version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-vehicle-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"    
      MYSQL_DATABASE: vehicle_db
      MYSQL_ROOT_PASSWORD: ""              
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - vehicle-net

  app:
    build: .
    container_name: spring-vehicle-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vehicle_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    networks:
      - vehicle-net

volumes:
  mysql_data:

networks:
  vehicle-net:
